# Generated by Django 5.2.2 on 2025-06-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название датчика')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('auth_login', models.CharField(max_length=255, verbose_name='Логин')),
                ('auth_password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('firmware_path', models.CharField(max_length=255, verbose_name='Путь для прошивки')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
            },
        ),
    ]
