# Generated by Django 5.2.2 on 2025-06-09 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Параметр 1')),
                ('param2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Параметр 2')),
                ('param3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Параметр 3')),
                ('param4', models.CharField(blank=True, max_length=10, null=True, verbose_name='Параметр 4')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
            },
        ),
    ]
